module.exports = [
  {
    name: 'Hilti BX-3',
    category: 'Tool',
    assigned: false,
    location: 'jigCO',
    assetTag: 37,
    uniqueID: '12345678',
  },
  {
    name: 'Fusion Splicer',
    category: 'Tool',
    assigned: true,
    location: 'Michael South',
    assetTag: 44,
    uniqueID: '10284659927',
  },
  {
    name: 'Galaxy X Cover Pro',
    category: 'Phone',
    assigned: true,
    location: 'John Smith',
    assetTag: 21,
    uniqueID: '3034712381',
  },
  {
    name: 'Galaxy X Cover Pro',
    category: 'Phone',
    assigned: true,
    location: 'Jane Smith',
    assetTag: 22,
    uniqueID: '7202539284',
  },
  {
    name: 'iPhone 12',
    category: 'Phone',
    assigned: true,
    location: 'Jerry Johnson',
    assetTag: 67,
    uniqueID: '3034948575',
  },
  {
    name: 'Macbook Pro',
    category: 'Laptop/Tablet',
    assigned: false,
    location: 'jigCO',
    assetTag: 90,
    uniqueID: '9020388502389',
  },
  {
    name: 'Surface Pro',
    category: 'Laptop/Tablet',
    assigned: true,
    location: 'Eddy Edwardson',
    assetTag: 49,
    uniqueID: '12345612945750078',
  },
  {
    name: 'Jiggsa-1902',
    category: 'Vehicle',
    assigned: true,
    location: 'James Jameson',
    assetTag: 1902,
    uniqueID: '1GHM8K10289598K78',
  },
  {
    name: 'Surface Pro',
    category: 'Laptop/Tablet',
    assigned: true,
    location: 'Bing Bongson',
    assetTag: 41,
    uniqueID: '12345615934850078',
  },
  {
    name: 'Jiggsa-1911',
    category: 'Vehicle',
    assigned: false,
    location: 'jigCO',
    assetTag: 1911,
    uniqueID: '1GHM8K18288549278K4',
  },

]
